### ISSUE TITLE
Plugin Handbook - Plugin Handbook

### ISSUE THREAD

**Issue by eric0324** [WordPress-Taiwan/document-l10n#1]
進行頁面 [Plugin Handbook](https://developer.wordpress.org/plugins/) 的本地化

**Comment by huanyichuang** [comment]
@eric0324 我把 index.md 裡的內容看完並編輯了，主要有幾個地方要注意:
* 有中國用語，例如信息 (information)
* 降低第二人稱的使用頻率
* 統一譯文一致性：譯文中出現《WordPress 外掛開發人員手冊》跟《WordPress 外掛開發者手冊》兩種指涉同一概念的名詞
* 標點符號使用：如果是章節、頁面名稱時，應該使用〈〉，如果是手冊首頁或網站名稱，則用《》

**Comment by huanyichuang** [comment]
@eric0324 你可以把網站那邊的草稿更新嗎？更新完之後我就來發布

**Comment by eric0324** [comment]
@huanyichuang 已經送交審閱囉
